server:
  port: 9090
spring:
  application:
    name: FD-API-GATEWAY-SERVICE

  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: FD-RESTAURANT-SERVICE
          uri: lb://FD-RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: FD-ORDER-SERVICE
          uri: lb://FD-ORDER-SERVICE
          predicates:
            - Path=/order/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: FD-FOOD-CATALOGUE-SERVICE
          uri: lb://FD-FOOD-CATALOGUE-SERVICE
          predicates:
            - Path=/foodCatalogue/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: FD-USER-SERVICE
          uri: lb://FD-USER-SERVICE
          predicates:
            - Path=/user/**





